#!/usr/bin/env php
<?php

/**
 * Populates the demo site. Assumes `helix` is already installed on the server
 * or location where this site is generated.
 */

$op = null;

if (isset($_SERVER['argv'][1])) {
    $op = $_SERVER['argv'][1];
}

$swd = dirname(realpath($_SERVER['argv'][0]));


include_once(dirname($swd) .'/bin/lib/Helpers.php');

success("RUN", 'Installing helix');

exec("cd $swd && helix setup -force");

success("RUN", 'Installing all helix components');
exec("cd $swd && helix install -all");
exec("cd $swd && grunt");
